### ISSUE TITLE
Instructions/code outdated

### ISSUE THREAD

**Issue by Efimero** [rnate/TES3MP-GraphicHerbalism#1]
tried to install this on a recent tes3mp server, but the line references on step 2a does not exist and grepping the scripts doesn't show any objectRefId anywhere =/

**Comment by rnate** [comment]
Yes, this is quite outdated now unfortunately. I would recommend using QuickHarvesting as an alternative. https://github.com/uramer/Tes3MP-Scripts/tree/master/QuickHarvesting
